### PR TITLE
Preloader fixes 

### LINKED ISSUE #34: Preloader

### PR DESCRIPTION
**Pull request by yuvraajnarula**
Fixes #34

### CODE REVIEW

**Comment by yuvraajnarula** [comment]
Screenshot (45)
Screenshot (46)

**Comment by yuvraajnarula** [comment]
yuvraajnarula.github.io/website2 @ion05 @Pulkitchamp

**Comment by ion05** [comment]
image
Why is there no padding between the 4 profile cards now ?

**Comment by yuvraajnarula** [comment]
@ion05 
Screenshot (47)

**Comment by ion05** [comment]
Make it what it was before

**Review by ion05 — APPROVED** [review]

**Pull request merged**
